import type { Departamento } from "@/components/CatalogoDepartamentos";

type CantidadDormitorios = 1 | 2 | 3;

const dimensionesPorDormitorio: Record<CantidadDormitorios, Departamento["dimensiones"]> = {
  1: [
    { ambiente: "Sala-comedor", medida: "4.50 × 3.20 m" },
    { ambiente: "Cocina", medida: "2.60 × 2.10 m" },
    { ambiente: "Dormitorio principal", medida: "3.20 × 3.00 m" },
    { ambiente: "Baño", medida: "2.10 × 1.50 m" },
    { ambiente: "Balcón", medida: "2.80 × 1.20 m" },
    { ambiente: "Lavandería", medida: "1.50 × 1.20 m" },
  ],

  2: [
    { ambiente: "Sala-comedor", medida: "5.20 × 3.40 m" },
    { ambiente: "Cocina", medida: "2.80 × 2.30 m" },
    { ambiente: "Dormitorio principal", medida: "3.40 × 3.10 m" },
    { ambiente: "Dormitorio secundario", medida: "3.00 × 2.70 m" },
    { ambiente: "Baño principal", medida: "2.20 × 1.50 m" },
    { ambiente: "Baño secundario", medida: "2.00 × 1.40 m" },
    { ambiente: "Balcón", medida: "3.20 × 1.20 m" },
  ],

  3: [
    { ambiente: "Sala-comedor", medida: "5.80 × 3.60 m" },
    { ambiente: "Cocina", medida: "3.00 × 2.50 m" },
    { ambiente: "Dormitorio principal", medida: "3.60 × 3.20 m" },
    { ambiente: "Dormitorio 2", medida: "3.00 × 2.80 m" },
    { ambiente: "Dormitorio 3", medida: "2.90 × 2.70 m" },
    { ambiente: "Baño principal", medida: "2.30 × 1.60 m" },
    { ambiente: "Baño compartido", medida: "2.10 × 1.50 m" },
    { ambiente: "Balcón", medida: "3.80 × 1.30 m" },
  ],
};

function crearDepartamento(
  id: string,
  modelo: string,
  dormitorios: CantidadDormitorios,
  banos: number,
  areaTotal: number,
  areaTechada: number,
  precio: number,
  piso: string,
  plano: string,
): Departamento {
  return {
    id,
    modelo,
    dormitorios,
    banos,
    areaTotal,
    areaTechada,
    precio,
    piso,
    plano,
    dimensiones: dimensionesPorDormitorio[dormitorios],
  };
}

export const departamentosPorProyecto = {
  autumn: [
    crearDepartamento(
      "autumn-a1",
      "Autumn A1",
      1,
      1,
      38,
      34,
      326000,
      "3 al 8",
      "/planos/autumn-a1.png",
    ),
    crearDepartamento(
      "autumn-a2",
      "Autumn A2",
      1,
      1,
      44,
      39,
      349000,
      "9 al 15",
      "/planos/autumn-a2.png",
    ),
    crearDepartamento(
      "autumn-b1",
      "Autumn B1",
      2,
      2,
      61,
      56,
      439000,
      "4 al 12",
      "/planos/autumn-b1.png",
    ),
    crearDepartamento(
      "autumn-b2",
      "Autumn B2",
      2,
      2,
      68,
      62,
      478000,
      "6 al 16",
      "/planos/autumn-b2.png",
    ),
    crearDepartamento(
      "autumn-c1",
      "Autumn C1",
      3,
      2,
      92,
      84,
      598000,
      "7 al 17",
      "/planos/autumn-c1.png",
    ),
    crearDepartamento(
      "autumn-c2",
      "Autumn C2",
      3,
      2,
      99,
      90,
      649000,
      "12 al 18",
      "/planos/autumn-c2.png",
    ),
  ],

  losalisos: [
    crearDepartamento(
      "alisos-b1",
      "Los Alisos B1",
      2,
      1,
      55,
      51,
      238000,
      "2 al 8",
      "/planos/los-alisos-b1.png",
    ),
    crearDepartamento(
      "alisos-b2",
      "Los Alisos B2",
      2,
      2,
      67,
      61,
      285000,
      "4 al 12",
      "/planos/los-alisos-b2.png",
    ),
    crearDepartamento(
      "alisos-c1",
      "Los Alisos C1",
      3,
      2,
      84,
      78,
      349000,
      "3 al 10",
      "/planos/los-alisos-c1.png",
    ),
    crearDepartamento(
      "alisos-c2",
      "Los Alisos C2",
      3,
      2,
      91,
      84,
      379000,
      "6 al 12",
      "/planos/los-alisos-c2.png",
    ),
  ],

  universitaria: [
    crearDepartamento(
      "universitaria-a1",
      "Universitaria A1",
      1,
      1,
      45,
      41,
      279000,
      "3 al 9",
      "/planos/universitaria-a1.png",
    ),
    crearDepartamento(
      "universitaria-a2",
      "Universitaria A2",
      1,
      1,
      49,
      44,
      299000,
      "10 al 16",
      "/planos/universitaria-a2.png",
    ),
    crearDepartamento(
      "universitaria-b1",
      "Universitaria B1",
      2,
      2,
      59,
      54,
      348000,
      "4 al 12",
      "/planos/universitaria-b1.png",
    ),
    crearDepartamento(
      "universitaria-b2",
      "Universitaria B2",
      2,
      2,
      65,
      59,
      379000,
      "7 al 17",
      "/planos/universitaria-b2.png",
    ),
    crearDepartamento(
      "universitaria-c1",
      "Universitaria C1",
      3,
      2,
      76,
      70,
      425000,
      "5 al 14",
      "/planos/universitaria-c1.png",
    ),
    crearDepartamento(
      "universitaria-c2",
      "Universitaria C2",
      3,
      2,
      82,
      75,
      459000,
      "10 al 18",
      "/planos/universitaria-c2.png",
    ),
  ],

  losrosales: [
    crearDepartamento(
      "rosales-b1",
      "Los Rosales B1",
      2,
      2,
      68,
      63,
      498000,
      "2 al 7",
      "/planos/los-rosales-b1.png",
    ),
    crearDepartamento(
      "rosales-b2",
      "Los Rosales B2",
      2,
      2,
      76,
      70,
      559000,
      "4 al 10",
      "/planos/los-rosales-b2.png",
    ),
    crearDepartamento(
      "rosales-c1",
      "Los Rosales C1",
      3,
      3,
      118,
      109,
      798000,
      "3 al 8",
      "/planos/los-rosales-c1.png",
    ),
    crearDepartamento(
      "rosales-c2",
      "Los Rosales C2",
      3,
      3,
      126,
      116,
      849000,
      "6 al 10",
      "/planos/los-rosales-c2.png",
    ),
  ],

  santacatalina: [
    crearDepartamento(
      "santa-catalina-a1",
      "Santa Catalina A1",
      1,
      1,
      42,
      38,
      265000,
      "3 al 10",
      "/planos/santa-catalina-a1.png",
    ),
    crearDepartamento(
      "santa-catalina-a2",
      "Santa Catalina A2",
      1,
      1,
      47,
      42,
      288000,
      "8 al 15",
      "/planos/santa-catalina-a2.png",
    ),
    crearDepartamento(
      "santa-catalina-b1",
      "Santa Catalina B1",
      2,
      2,
      57,
      53,
      329000,
      "4 al 14",
      "/planos/santa-catalina-b1.png",
    ),
    crearDepartamento(
      "santa-catalina-b2",
      "Santa Catalina B2",
      2,
      2,
      63,
      58,
      359000,
      "7 al 16",
      "/planos/santa-catalina-b2.png",
    ),
    crearDepartamento(
      "santa-catalina-c1",
      "Santa Catalina C1",
      3,
      2,
      74,
      68,
      409000,
      "6 al 16",
      "/planos/santa-catalina-c1.png",
    ),
    crearDepartamento(
      "santa-catalina-c2",
      "Santa Catalina C2",
      3,
      2,
      82,
      75,
      449000,
      "10 al 18",
      "/planos/santa-catalina-c2.png",
    ),
  ],
} satisfies Record<string, Departamento[]>;

export type ProyectoDepartamentos = keyof typeof departamentosPorProyecto;

export function getDepartamentos(proyecto: ProyectoDepartamentos): Departamento[] {
  return departamentosPorProyecto[proyecto];
}
