/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProyectoLosrosalesRouteImport } from './routes/proyecto-losrosales'
import { Route as ProyectoSantacatalinaRouteImport } from './routes/proyecto-santacatalina'
import { Route as Proyecto_albaRouteImport } from './routes/proyecto_alba'
import { Route as Proyecto_autummRouteImport } from './routes/proyecto_autumm'
import { Route as Proyecto_losalisosRouteImport } from './routes/proyecto_losalisos'
import { Route as Proyecto_universitariaRouteImport } from './routes/proyecto_universitaria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoLosrosalesRoute = ProyectoLosrosalesRouteImport.update({
  id: '/proyecto-losrosales',
  path: '/proyecto-losrosales',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoSantacatalinaRoute = ProyectoSantacatalinaRouteImport.update({
  id: '/proyecto-santacatalina',
  path: '/proyecto-santacatalina',
  getParentRoute: () => rootRouteImport,
} as any)
const Proyecto_albaRoute = Proyecto_albaRouteImport.update({
  id: '/proyecto_alba',
  path: '/proyecto_alba',
  getParentRoute: () => rootRouteImport,
} as any)
const Proyecto_autummRoute = Proyecto_autummRouteImport.update({
  id: '/proyecto_autumm',
  path: '/proyecto_autumm',
  getParentRoute: () => rootRouteImport,
} as any)
const Proyecto_losalisosRoute = Proyecto_losalisosRouteImport.update({
  id: '/proyecto_losalisos',
  path: '/proyecto_losalisos',
  getParentRoute: () => rootRouteImport,
} as any)
const Proyecto_universitariaRoute = Proyecto_universitariaRouteImport.update({
  id: '/proyecto_universitaria',
  path: '/proyecto_universitaria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proyecto-losrosales': typeof ProyectoLosrosalesRoute
  '/proyecto-santacatalina': typeof ProyectoSantacatalinaRoute
  '/proyecto_alba': typeof Proyecto_albaRoute
  '/proyecto_autumm': typeof Proyecto_autummRoute
  '/proyecto_losalisos': typeof Proyecto_losalisosRoute
  '/proyecto_universitaria': typeof Proyecto_universitariaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proyecto-losrosales': typeof ProyectoLosrosalesRoute
  '/proyecto-santacatalina': typeof ProyectoSantacatalinaRoute
  '/proyecto_alba': typeof Proyecto_albaRoute
  '/proyecto_autumm': typeof Proyecto_autummRoute
  '/proyecto_losalisos': typeof Proyecto_losalisosRoute
  '/proyecto_universitaria': typeof Proyecto_universitariaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/proyecto-losrosales': typeof ProyectoLosrosalesRoute
  '/proyecto-santacatalina': typeof ProyectoSantacatalinaRoute
  '/proyecto_alba': typeof Proyecto_albaRoute
  '/proyecto_autumm': typeof Proyecto_autummRoute
  '/proyecto_losalisos': typeof Proyecto_losalisosRoute
  '/proyecto_universitaria': typeof Proyecto_universitariaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/proyecto-losrosales'
    | '/proyecto-santacatalina'
    | '/proyecto_alba'
    | '/proyecto_autumm'
    | '/proyecto_losalisos'
    | '/proyecto_universitaria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/proyecto-losrosales'
    | '/proyecto-santacatalina'
    | '/proyecto_alba'
    | '/proyecto_autumm'
    | '/proyecto_losalisos'
    | '/proyecto_universitaria'
  id:
    | '__root__'
    | '/'
    | '/proyecto-losrosales'
    | '/proyecto-santacatalina'
    | '/proyecto_alba'
    | '/proyecto_autumm'
    | '/proyecto_losalisos'
    | '/proyecto_universitaria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProyectoLosrosalesRoute: typeof ProyectoLosrosalesRoute
  ProyectoSantacatalinaRoute: typeof ProyectoSantacatalinaRoute
  Proyecto_albaRoute: typeof Proyecto_albaRoute
  Proyecto_autummRoute: typeof Proyecto_autummRoute
  Proyecto_losalisosRoute: typeof Proyecto_losalisosRoute
  Proyecto_universitariaRoute: typeof Proyecto_universitariaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-losrosales': {
      id: '/proyecto-losrosales'
      path: '/proyecto-losrosales'
      fullPath: '/proyecto-losrosales'
      preLoaderRoute: typeof ProyectoLosrosalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-santacatalina': {
      id: '/proyecto-santacatalina'
      path: '/proyecto-santacatalina'
      fullPath: '/proyecto-santacatalina'
      preLoaderRoute: typeof ProyectoSantacatalinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto_alba': {
      id: '/proyecto_alba'
      path: '/proyecto_alba'
      fullPath: '/proyecto_alba'
      preLoaderRoute: typeof Proyecto_albaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto_autumm': {
      id: '/proyecto_autumm'
      path: '/proyecto_autumm'
      fullPath: '/proyecto_autumm'
      preLoaderRoute: typeof Proyecto_autummRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto_losalisos': {
      id: '/proyecto_losalisos'
      path: '/proyecto_losalisos'
      fullPath: '/proyecto_losalisos'
      preLoaderRoute: typeof Proyecto_losalisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto_universitaria': {
      id: '/proyecto_universitaria'
      path: '/proyecto_universitaria'
      fullPath: '/proyecto_universitaria'
      preLoaderRoute: typeof Proyecto_universitariaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProyectoLosrosalesRoute: ProyectoLosrosalesRoute,
  ProyectoSantacatalinaRoute: ProyectoSantacatalinaRoute,
  Proyecto_albaRoute: Proyecto_albaRoute,
  Proyecto_autummRoute: Proyecto_autummRoute,
  Proyecto_losalisosRoute: Proyecto_losalisosRoute,
  Proyecto_universitariaRoute: Proyecto_universitariaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
